on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
